trigger:
- main  # ou o nome do seu branch principal

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

- script: npm install
  displayName: 'Instalar dependências'

- script: npm test
  displayName: 'Rodar testes'
